name: PGM Metrics

on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: 'ryan112358'
          repo: 'mbi'

          filename: metrics.mbi.svg

          # --- Configure the base sections ---
          # The 'repositories' section here will be filtered by 'filter_pattern'.
          # You might want to keep 'header' if it shows the repo name based on filter.
          # 'activity', 'community' might show less relevant info when filtered to a single repo.
          # Experiment with what looks best for a single-repository view.
          base: header, repositories # Adjust as needed, e.g., some users remove 'community' for repo views

          # Displays contributors to the filtered repository.
          # Check plugin documentation for specific options if needed.
          plugin_contributors: yes

          # For traffic data, token needs admin/push access to the target repository.
          plugin_traffic: yes

          template: repository

          config_order: base.header, base.repositories, traffic, isocalendar, languages, lines, contributors
